apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: admin-service
spec:
  host: admin-service
  subsets:
  - name: v1
    labels:
      version: v1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: faculty-service
spec:
  host: faculty-service
  subsets:
  - name: v1
    labels:
      version: v1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: student-service
spec:
  host: student-service
  subsets:
  - name: v1
    labels:
      version: v1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL