apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: admin-service
spec:
  hosts:
  - "admin-service"
  http:
  - route:
    - destination:
        host: admin-service
        subset: v1
      weight: 100

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: faculty-service
spec:
  hosts:
  - "faculty-service"
  http:
  - route:
    - destination:
        host: faculty-service
        subset: v1
      weight: 100

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: student-service
spec:
  hosts:
  - "student-service"
  http:
  - route:
    - destination:
        host: student-service
        subset: v1
      weight: 100

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-gateway
spec:
  hosts:
  - "*"
  gateways:
  - public-gateway
  http:
  - match:
    - uri:
        prefix: /admin
    route:
    - destination:
        host: admin-service
        port:
          number: 4001
  - match:
    - uri:
        prefix: /faculty
    route:
    - destination:
        host: faculty-service
        port:
          number: 4002
  - match:
    - uri:
        prefix: /student
    route:
    - destination:
        host: student-service
        port:
          number: 4003