
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: LoadBalancer
  selector:
    app: eureka-server
  ports:
  - name: http-eureka  # Changed to follow Istio convention
    protocol: TCP
    port: 8761
    targetPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  type: LoadBalancer
  selector:
    app: admin-service
  ports:
  - name: http-admin  # Changed to follow Istio convention
    protocol: TCP
    port: 4001
    targetPort: 4001

---

apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    app: student-service
spec:
  type: LoadBalancer
  selector:
    app: student-service
  ports:
  - name: http-student  # Changed to follow Istio convention
    protocol: TCP
    port: 4003
    targetPort: 4003

---

apiVersion: v1
kind: Service
metadata:
  name: faculty-service
  labels:
    app: faculty-service
spec:
  type: LoadBalancer
  selector:
    app: faculty-service
  ports:
  - name: http-faculty  # Changed to follow Istio convention
    protocol: TCP
    port: 4002
    targetPort: 4002

---
# api-gateway-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway  # must match your deployment labels
  ports:
    - name: http-apigateway
      protocol: TCP
      port: 4000
      targetPort: 4000  # matches your Spring Boot server.port