apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001

---

apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    app: student-service
spec:
  selector:
    app: student-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4003

---

apiVersion: v1
kind: Service
metadata:
  name: faculty-service
  labels:
    app: faculty-service
spec:
  selector:
    app: faculty-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4002